### ISSUE TITLE
sriovnetworknodestates : lastSyncError: timed out waiting for the condition   syncStatus: InProgress

### ISSUE THREAD

**Issue by seb-835** [k8snetworkplumbingwg/sriov-network-operator#306] opened 2022-05-13 15:20 UTC
Hi Team,
i have deploy sriov-network-operator,
i have 4 nodes with infiniband card : Mellanox COnnect X-6,

one  node have the card  configured with VFS, using this method : 
 https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/master/docs/vf-setup.md#mellanox

But when querying  sriovnetworknodestates.sriovnetwork.openshift.io , this is  the only node with a never ended "syncStatus: InProgress"   

```
...
_lastSyncError: timed out waiting for the condition   
syncStatus: InProgress_
```

is it a bad or a normal behavior, before i goes further.
Best regards

**Comment by SchSeba** [comment] 2022-05-17 09:59
Hi @seb-835 please check the logs from the sriov-config-daemon it will give us more info on why that is the status of the CR

**Comment by seb-835** [comment] 2022-05-18 07:29
Hi @SchSeba ,

i check log, and see this : 

```
I0518 06:53:37.578868   49529 writer.go:132] setNodeStateStatus(): syncStatus: InProgress, lastSyncError: timed out waiting for the condition
I0518 06:53:40.049698   49529 request.go:655] Throttling request took 1.092779138s, request: GET:https://10.233.0.1:443/api/v1/namespaces/cattle-system/pods/rancher-6cb49ffd8f-7fppf
I0518 06:53:48.054043   49529 daemon.go:917] Draining failed with: [error when waiting for pod "rancher-monitoring-prometheus-adapter-8846d4757-lzhlg" terminating: global timeout reached: 1m30s, error when waiting for pod "python-k8s-deployment-64c7c9f7ff-j97hj" terminating: global timeout reached: 1m30s, error when waiting for pod "rancher-monitoring-grafana-0" terminating: global timeout reached: 1m30s, error when waiting for pod "prometheus-rancher-monitoring-prometheus-0" terminating: global timeout reached: 1m30s, error when waiting for pod "rancher-monitoring-operator-559767d69b-gxzh2" terminating: global timeout reached: 1m30s, error when waiting for pod "rancher-6cb49ffd8f-7fppf" terminating: global timeout reached: 1m30s], retrying
E0518 06:53:48.054088   49529 daemon.go:921] drainNode(): failed to drain node (5 tries): timed out waiting for the condition :[error when waiting for pod "rancher-monitoring-prometheus-adapter-8846d4757-lzhlg" terminating: global timeout reached: 1m30s, error when waiting for pod "python-k8s-deployment-64c7c9f7ff-j97hj" terminating: global timeout reached: 1m30s, error when waiting for pod "rancher-monitoring-grafana-0" terminating: global timeout reached: 1m30s, error when waiting for pod "prometheus-rancher-monitoring-prometheus-0" terminating: global timeout reached: 1m30s, error when waiting for pod "rancher-monitoring-operator-559767d69b-gxzh2" terminating: global timeout reached: 1m30s, error when waiting for pod "rancher-6cb49ffd8f-7fppf" terminating: global timeout reached: 1m30s]
E0518 06:53:48.054105   49529 daemon.go:923] drainNode(): failed to drain node: timed out waiting for the condition
```

and as soon as i clean pod in Terminating State,  sriovnetworknodestates.sriovnetwork.openshift.io come to syncstatus : success.

That s a strange behaviour that pods in "failed" terminating state in other namespace, impact the sriov-config-daemon work.

**Comment by seb-835** [comment] 2022-05-20 13:42
Hi @SchSeba ,

i got more informations,  faulty  SriovNetworkNodePolicy settings can break the discovery, with the syncStatus stuck  at inprogress .

The only solution is  :
  1- remove the  faulty  SriovNetworkNodePolicy , 
  2 - then delete the sriov-network-config-daemon pod

**Comment by SchSeba** [comment] 2022-05-26 11:10
Hi @seb-835 for the first comment that is by design the sriov operator needs to drain the node before is able to change the configuration (to be sure there are no pods running that use VFs)

for your second comment I was not able to understand the comment can you please explain a bit more?

**Comment by SchSeba** [comment] 2022-08-11 15:12
Hi @seb-835 any update here or we can close the issue?

**Comment by SchSeba** [comment] 2023-12-21 08:03
closing this issue feel free to reopen if needed

**Closed by SchSeba** 2023-12-21 08:03 UTC
